sudo: false
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
services:
  - postgresql
language: node_js
node_js:
- 8.11.4
before_install:
- npm install -g codecov
install:
- npm install
cache:
  directories:
  - "$HOME/.npm"
before_script:
  - psql -U postgres -c 'create database fastfoodfasttest;'
script:
- npm run initdb
- npm test
deploy:
  provider: heroku
  api_key:
    secure: z1pWiMk3DwWE9zh+VlstT6tuITYu/V4NFY03wnUey2O5Di8N82KB7dPXsa+FMheeEowhLZqgnDQipcVLeKmtOvhzl+dmfEbX3FVfePQtTsc5keknqwFCUHYD2TbX2sDGMONT77VMhQjhh87iLNZxzE2NC7vq8Lo2bBR5YCOncib6hleQ+O+jMv9HurIjBnP26m3nG+0ekpWN8GaisXTAZuKw9gsoKcCMScEmsK7Y6MMrcLXLswIEYbvzF2cVznnICqjejKGrU7eDeQljwO6zDME+U+TJsjrP1nc96Uj/Bq9Ycz/6hRGIBOuSPS7ZyHbo7UmrWpxReUIZ6GvFYiv+H0AJbtPVYy19QS+yPlKznRsr2UnnGwwWAvMJ+eWB3DuavYeUpMNHvEMtCBH25BlrGGbHi6+jawRl0OuzyUhm8VB3SzW4luiBamDdYx9uB7pIl6yiO9brjsrTwD8mFEFJa2fOVdFCPCKx6Tu8qEvXJZXq0XH4MvYugDbTiy9ZPgX0dWy9keSK3BKDCPBWEaEbipLYRqrY0Th990CFixlyZvgQl9SPYa4Qb7PjAfO3q9IVQL1zhWZAVJF0xP14l7qrqz8VCmmifyL2C798kimoCWUa/EqFBh+OTcraMmlkPWcgMjEkgLyQbQfaS1YfkKrI0qWTi8y5/GWhUqi6nJGGER8=
  app:
    develop: fast-food-fast-server
after_success: npm run coverage